apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: project-manager
  labels:
    app: flask-api
spec:
  selector:
    app: flask-api
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30000
  type: NodePort