apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: project-manager
type: Opaque
data:
  POSTGRES_PASSWORD: <base64-encoded-password>
  POSTGRES_DB: <base64-encoded-db-name>
  SECRET_KEY: <base64-encoded-secret-key>
  JWT_SECRET_KEY: <base64-encoded-jwt-key>